"""initial_v2

Revision ID: 2c34231c6375
Revises: 
Create Date: 2026-07-11 21:47:47.828629
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '2c34231c6375'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_sessions')
    op.add_column('answer_records', sa.Column('attempt_id', sa.Integer(), nullable=False))
    op.add_column('answer_records', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.alter_column('answer_records', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('answer_records', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('answer_records_user_id_question_id_key'), 'answer_records', type_='unique')
    op.drop_constraint(op.f('answer_records_chapter_id_fkey'), 'answer_records', type_='foreignkey')
    op.create_foreign_key(None, 'answer_records', 'chapter_attempts', ['attempt_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answer_records', 'chapter_id')
    op.add_column('chapters', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('chapters', 'rag_chunk_count')
    op.drop_column('chapters', 'rag_doc_count')
    op.add_column('chat_messages', sa.Column('session_id', sa.Integer(), nullable=False))
    op.add_column('chat_messages', sa.Column('sources', sa.JSON(), nullable=True))
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('chat_messages_course_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_chapter_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_user_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'chapter_id')
    op.drop_column('chat_messages', 'user_id')
    op.drop_column('chat_messages', 'course_id')
    op.add_column('courses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('learning_objectives', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('review_prompt', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('chat_prompt', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('recommend_prompt', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.drop_column('courses', 'goals')
    op.drop_column('courses', 'prompt_recommend')
    op.drop_column('courses', 'intro')
    op.drop_column('courses', 'prompt_review')
    op.drop_column('courses', 'prompt_reply')
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('heading', sa.String(length=500), nullable=True))
    op.add_column('document_chunks', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('document_chunks', 'course_id')
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('documents_course_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'course_id')
    op.add_column('questions', sa.Column('import_batch_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'questions', 'question_import_batches', ['import_batch_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('wrong_questions', sa.Column('attempt_id', sa.Integer(), nullable=True))
    op.alter_column('wrong_questions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wrong_questions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wrong_questions', 'chapter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('wrong_questions_user_id_question_id_key'), 'wrong_questions', type_='unique')
    op.create_foreign_key(None, 'wrong_questions', 'chapter_attempts', ['attempt_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wrong_questions', type_='foreignkey')
    op.create_unique_constraint(op.f('wrong_questions_user_id_question_id_key'), 'wrong_questions', ['user_id', 'question_id'])
    op.alter_column('wrong_questions', 'chapter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wrong_questions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wrong_questions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('wrong_questions', 'attempt_id')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'is_active')
    op.drop_column('questions', 'import_batch_id')
    op.add_column('documents', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('documents_course_id_fkey'), 'documents', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'file_size')
    op.add_column('document_chunks', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('document_chunks', 'extra_metadata')
    op.drop_column('document_chunks', 'heading')
    op.drop_column('document_chunks', 'page_number')
    op.add_column('courses', sa.Column('prompt_reply', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('prompt_review', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('intro', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('prompt_recommend', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('goals', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('courses', 'sort_order')
    op.drop_column('courses', 'recommend_prompt')
    op.drop_column('courses', 'chat_prompt')
    op.drop_column('courses', 'review_prompt')
    op.drop_column('courses', 'learning_objectives')
    op.drop_column('courses', 'description')
    op.add_column('chat_messages', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_user_id_fkey'), 'chat_messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('chat_messages_chapter_id_fkey'), 'chat_messages', 'chapters', ['chapter_id'], ['id'])
    op.create_foreign_key(op.f('chat_messages_course_id_fkey'), 'chat_messages', 'courses', ['course_id'], ['id'])
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('chat_messages', 'sources')
    op.drop_column('chat_messages', 'session_id')
    op.add_column('chapters', sa.Column('rag_doc_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chapters', sa.Column('rag_chunk_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('chapters', 'updated_at')
    op.add_column('answer_records', sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer_records', type_='foreignkey')
    op.create_foreign_key(op.f('answer_records_chapter_id_fkey'), 'answer_records', 'chapters', ['chapter_id'], ['id'])
    op.create_unique_constraint(op.f('answer_records_user_id_question_id_key'), 'answer_records', ['user_id', 'question_id'])
    op.alter_column('answer_records', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('answer_records', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('answer_records', 'duration_seconds')
    op.drop_column('answer_records', 'attempt_id')
    op.create_table('chapter_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('chapter_sessions_chapter_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chapter_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chapter_sessions_pkey')),
    sa.UniqueConstraint('user_id', 'chapter_id', name=op.f('chapter_sessions_user_id_chapter_id_key'))
    )
    # ### end Alembic commands ###
